### ISSUE TITLE
Cannot build Jupyter Book documentation

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-Core#849]
All of the `docs_check.yml` and `deploy_docs.yml` tests are currently passing in the `OG-Core` repository. However, I cannot get the documentation to build in OG-Core or any of the other country calibrations using the `jb build ./docs/book` command.

Because `jupyter-book` and `sphinxcontrib-bibtex` are not in the `environment.py` or `setup.py` files, I do the following steps.
* Create `ogcore-dev` conda environment: `conda env create -f environment.yml`
* Activate `ogcore-dev` conda environment: `conda activate ogcore-dev`
* Install `ogcore` package to conda environement: `pip install -e .`
* Install `jupyter-book` package: `pip install jupyter-book`
* Install `sphinxcontrib-bibtex` package: `pip install sphinxcontrib-bibtex`
* Build Jupyter Book documentation: `jb build ./docs/book`

When I first did this, I got the following error.
```
exception: jsonschema 3.2.0 has no such extra feature 'format-nongpl'
```
This [`jupyter-book` GitHub issue](https://github.com/executablebooks/jupyter-book/issues/1902) proposed setting the `_config.yml` execute setting to `force` instead of `cache`.
```yml
# Execution settings
execute:
  execute_notebooks      : force
```
[This issue](https://github.com/executablebooks/jupyter-book/issues/1907) gives an even more detailed discussion of how and why the original error arises and that the `cache` option can be used again once a new version of `jupyter-book` is merged.

Once I made that change to `_config.yml`, that error went away and I started getting this new error, which I cannot get to go away.
```
  File "/opt/anaconda3/envs/ogcore-dev/lib/python3.10/site-packages/jupyter_client/kernelspec.py", line 287, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named ogcore-dev
```
I tried installing `ipython` and I tried installing `jupyter` (general notebooks), but none of those packages solved this issue.

cc: @jdebacker

**Comment by jdebacker** [comment]
@rickecon Confirmed a failure on my machine with Jupyter Book 0.11.3:

```
(base) jason.debacker@JDEBACKER docs % jb build ./book
Running Jupyter-Book v0.11.3
Source Folder: /Users/jason.debacker/repos/OG-Core/docs/book
Config Path: /Users/jason.debacker/repos/OG-Core/docs/book/_config.yml
Output Path: /Users/jason.debacker/repos/OG-Core/docs/book/_build/html
Running Sphinx v5.0.2
loading translations [None]... not available for built-in messages
WARNING: cannot override config setting 'html_add_permalinks' with unsupported type, ignoring
WARNING: The config value `language' has type `NoneType'; expected `str'.

Extension error (sphinx.config):
Handler <function check_confval_types at 0x7fa33877f5f0> for event 'config-inited' threw an exception (exception: 'NoneType' object has no attribute 'startswith')
Traceback (most recent call last):
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/sphinx/config.py", line 431, in check_confval_types
    default = default(config)  # evaluate default value
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 468, in default_latex_engine
    elif config.language.startswith('zh'):
AttributeError: 'NoneType' object has no attribute 'startswith'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 128, in build_sphinx
    keep_going=keep_going,
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 247, in __init__
    self.events.emit('config-inited', self.config)
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    (listener.handler, name), exc, modname=modname) from exc
sphinx.errors.ExtensionError: Handler <function check_confval_types at 0x7fa33877f5f0> for event 'config-inited' threw an exception (exception: 'NoneType' object has no attribute 'startswith')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jason.debacker/anaconda3/bin/jb", line 8, in <module>
    sys.exit(main())
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/jupyter_book/cli/main.py", line 320, in build
    result, builder, OUTPUT_PATH, build_type, PAGE_NAME, click.echo
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/jupyter_book/cli/main.py", line 519, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
```

**Comment by jdebacker** [comment]
@rickecon Have you tried [making a kernel of the `ogcore-dev` virtual environment](https://towardsdatascience.com/link-your-virtual-environment-to-jupyter-with-kernels-a69bc61728df).

In the command line, and after installing `ipykernel`, you can do:

```
python -m ipykernel install --user --name=ogcore-dev
```

**Comment by jdebacker** [comment]
Follow up -- after creating the `ogcore-dev` kernel, the book built, though there are some warnings:

```
(ogcore-dev) jason.debacker@JDEBACKER docs % jb build ./book
Running Jupyter-Book v0.13.1
Source Folder: /Users/jason.debacker/repos/OG-Core/docs/book
Config Path: /Users/jason.debacker/repos/OG-Core/docs/book/_config.yml
Output Path: /Users/jason.debacker/repos/OG-Core/docs/book/_build/html
Running Sphinx v4.5.0
[etoc] Changing master_doc to 'content/intro/intro'
checking bibtex cache... out of date
parsing bibtex file /Users/jason.debacker/repos/OG-Core/docs/book/OGCore_references.bib... parsed 28 entries
parsing bibtex file /Users/jason.debacker/repos/OG-Core/docs/book/citations.bib... parsed 18 entries
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 30 source files that are out of date
updating environment: [new config] 30 added, 0 changed, 0 removed
Executing: content/theory/demographics in: /Users/jason.debacker/repos/OG-Core/docs/book/content/theory
Executing: content/theory/households in: /Users/jason.debacker/repos/OG-Core/docs/book/content/theory
reading sources... [100%] content/theory/stationarization
/Users/jason.debacker/repos/OG-Core/ogcore/aggregates.py:docstring of ogcore.aggregates.revenue:50: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/aggregates.py:docstring of ogcore.aggregates.revenue:51: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/aggregates.py:docstring of ogcore.aggregates.revenue:55: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/aggregates.py:docstring of ogcore.aggregates.revenue:59: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/aggregates.py:docstring of ogcore.aggregates.revenue:60: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/elliptical_u_est.py:docstring of ogcore.elliptical_u_est:1: CRITICAL: Missing matching underline for section title overline.

------------------------------------------------------------------------
This script takes a Frisch elasticity parameter and then estimates the
parameters of the elliptical utility fuction that correspond to a
/Users/jason.debacker/repos/OG-Core/ogcore/elliptical_u_est.py:docstring of ogcore.elliptical_u_est.estimation:11: ERROR: Unexpected indentation.
WARNING: missing attribute mentioned in :members: option: module ogcore.firm, attribute get_KLratio_old
WARNING: missing attribute mentioned in :members: option: module ogcore.firm, attribute get_K_from_Y
WARNING: missing attribute mentioned in :members: option: module ogcore.firm, attribute get_K_from_Y_and_L
WARNING: missing attribute mentioned in :members: option: module ogcore.firm, attribute get_K_new
WARNING: missing attribute mentioned in :members: option: module ogcore.household, attribute get_cm
/Users/jason.debacker/repos/OG-Core/ogcore/output_plots.py:docstring of ogcore.output_plots.plot_aggregates:17: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/output_plots.py:docstring of ogcore.output_plots.plot_aggregates:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/output_plots.py:docstring of ogcore.output_plots.plot_aggregates:20: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/output_plots.py:docstring of ogcore.output_plots.plot_aggregates:22: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/output_plots.py:docstring of ogcore.output_plots.plot_gdp_ratio:17: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/output_plots.py:docstring of ogcore.output_plots.plot_gdp_ratio:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/docs/book/content/api/output_tables.rst:6: WARNING: Inline strong start-string without end-string.
/Users/jason.debacker/repos/OG-Core/ogcore/output_tables.py:docstring of ogcore.output_tables.dynamic_revenue_decomposition:49: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/output_tables.py:docstring of ogcore.output_tables.dynamic_revenue_decomposition:51: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/output_tables.py:docstring of ogcore.output_tables.dynamic_revenue_decomposition:61: WARNING: Enumerated list ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/output_tables.py:docstring of ogcore.output_tables.macro_table:17: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/output_tables.py:docstring of ogcore.output_tables.macro_table:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/parameters.py:docstring of ogcore.parameters.Specifications.update_specifications:24: ERROR: Unexpected indentation.
/Users/jason.debacker/repos/OG-Core/ogcore/parameters.py:docstring of ogcore.parameters.Specifications.update_specifications:26: WARNING: Literal block ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/docs/book/content/api/public_api.rst:11: WARNING: toctree directive not expected with external-toc [etoc.toctree]
/Users/jason.debacker/repos/OG-Core/ogcore/tax.py:docstring of ogcore.tax.get_biz_tax:6: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/Users/jason.debacker/repos/OG-Core/ogcore/txfunc.py:docstring of ogcore.txfunc:1: CRITICAL: Missing matching underline for section title overline.

------------------------------------------------------------------------
This script reads in data generated from the Tax Calculator model.
It then estimates tax functions tau_{s,t}(x,y), where
/Users/jason.debacker/repos/OG-Core/ogcore/txfunc.py:docstring of ogcore.txfunc.txfunc_est:30: WARNING: Bullet list ends without a blank line; unexpected unindent.
WARNING: missing attribute topshare in object ogcore.utils.Inequality
/Users/jason.debacker/repos/OG-Core/ogcore/utils.py:docstring of ogcore.utils.get_initial_path:23: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/jason.debacker/repos/OG-Core/docs/book/content/contributing/contributor_guide.md:0: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/equilibrium.md:353: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/financial.md:17: WARNING: duplicate label of equation EqMarkClr_zetaD2, other instance in content/theory/financial
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/financial.md:: CRITICAL: Duplicate ID: "equation-eqmarkclr-zetad2".
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/financial.md:53: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/firms.md:112: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/government.md:34: WARNING: Non-consecutive header level increase; 4 to 6 [myst.header]
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/government.md:561: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/households.md:205: WARNING: duplicate label of equation EqHHBC2, other instance in content/theory/government
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/households.md:235: WARNING: duplicate label of equation EqMTRx_derive, other instance in content/theory/government
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/households.md:240: WARNING: duplicate label of equation EqMTRy_derive, other instance in content/theory/government
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/households.md:294: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/households.md:16: WARNING: duplicate label glue, other instance in /Users/jason.debacker/repos/OG-Core/docs/book/content/theory/demographics.md
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/intro.md:2: WARNING: duplicate label chap_intro, other instance in /Users/jason.debacker/repos/OG-Core/docs/book/content/intro/intro.md
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/market_clearing.md:140: ERROR: Document or section may not begin with a transition.
/Users/jason.debacker/repos/OG-Core/docs/book/content/citations.md:3: WARNING: duplicate label "DEP19" for keys "DeBackerEtAl:2019" and "DEP:2019"
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] content/theory/stationarization
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/equilibrium.md:93: WARNING: equation not found: EqHH_cmDem
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/equilibrium.md:199: WARNING: undefined label: chap_calibr
/Users/jason.debacker/repos/OG-Core/docs/book/content/theory/equilibrium.md:331: WARNING: equation not found: EqHH_cmDem
generating indices... genindex py-modindex done
highlighting module code... [100%] ogcore.utils
writing additional pages... search done
copying images... [ 85%] _build/jupyter_execute/content/theory/households_1_1.pncopying images... [100%] content/theory/images/EllipVsCFE_MargUtil.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 51 warnings.

The HTML pages are in book/_build/html.

===============================================================================

Finished generating HTML for book.
Your book's HTML pages are here:
    book/_build/html/
You can look at your book by opening this file in a browser:
    book/_build/html/index.html
Or paste this line directly into your browser bar:
    file:///Users/jason.debacker/repos/OG-Core/docs/book/_build/html/index.html

===============================================================================
```

**Comment by rickecon** [comment]
@jdebacker. Yes. That works for me. And I guess we don't have to worry about this for the CI testing for some reason.

**Comment by rickecon** [comment]
@jdebacker. I am marking this as resolved. Thanks for finding the `ipykernel` solution.

**Comment by rickecon** [comment]
@jdebacker. I reopened this issue because these same problems are now occurring in the `docs_check.yml` and `deploy_docs.yml` tests (see PR #850).
